In [100]:
import matplotlib.pyplot as plt
import collections
import numpy as np
from numpy.linalg import inv
import warnings
import random
import math
from path import Path
warnings.simplefilter("ignore")
%matplotlib inline

In [2]:
def textPure(textNP):
    """Data una stringa, textPure ritorna una stringa priva disimboli jolly (,.;'(,)', # ecc..)
         e con tutti i caratteri in minuscolo"""
    for i in range(32,47):
        if(textNP.find(chr(i))>=0):
            textNP = textNP.replace(chr(i),"")
    if(textNP.find("\n")>=0):
        textNP = textNP.replace("\n","")
    textNP= textNP.lower()
    return textNP

In [85]:
def getArray(subString):
    array = []
    for i in range(len(subString)):
        array.append(ord(subString[i])-ord("a"))
    array = np.array(array)
    return array

In [6]:
ord("A")

65

In [32]:
a = getArray(textP[0:3])

array([108, 111, 118])

In [49]:
array = []
for i in range(0,15,3):
    array.append(getArray(textP[i:i+3]))
    #print(textP[i:i+3])
    
np.matrix(array)

matrix([[108, 111, 118],
        [101, 108, 111],
        [118, 101, 105],
        [115,  97, 118],
        [101, 114,  98]])

In [87]:
def buildMatrix(text,m):
    array = []
    for i in range(0,len(text)-m,m):
        array.append(getArray(text[i:i+m]))
    return np.matrix(array).T

In [77]:
plaintext = "friday"
cipertext = "pqcfku"
#t = chr(5+ord("a"))

In [54]:
t

'f'

In [61]:
t=ord("r")-ord("a")

In [62]:
t

17

In [65]:
getArray(textP)

5
17
8
3
0
24


array([ 5, 17,  8,  3,  0, 24])

In [90]:
P = buildMatrix(plaintext,2)

In [189]:
P

matrix([[ 5,  8],
        [17,  3]])

In [91]:
C =buildMatrix(cipertext,2)

In [96]:
detP = round(np.linalg.det(P))%26

In [97]:
detP

9.0

In [99]:
math.gcd(int(detP), 26)

1

In [197]:
#invP = inv(P)*detP
#invP = inv(P)
inv(P)*modInverse(detP, 26)

matrix([[-0.07438017,  0.19834711],
        [ 0.4214876 , -0.12396694]])

In [175]:
invDetP= math.pow(detP,-1)

In [180]:
pow(invDetP%26,-1)

9.0

In [161]:
C = np.matrix(np.copy(P))

In [181]:
def modInverse(a, m) : 
    a = a % m; 
    for x in range(1, m) : 
        if ((a * x) % m == 1) : 
            return x 
    return 1

In [201]:
modInverse(9, 26)

3

In [188]:
M

0.1111111111111111

In [212]:
m = np.matrix([[5, 8], [17, 3]])
invP = inv(m)*round(np.linalg.det(P))*modInverse(round(np.linalg.det(P)), 26)

In [219]:
for i in range(len(invP)):
    for j in range(len(invP)):
        invP[i,j] = invP[i,j]%26
invP

matrix([[ 9.,  2.],
        [ 1., 15.]])

In [228]:
plaintext = "friday"
cipertext = "pqcfku"
P = buildMatrix(plaintext,2)
C = buildMatrix(cipertext,2)
invP = inv(P)*int(np.linalg.det(P))*modInverse(int(np.linalg.det(P)), 26)
for i in range(len(invP)):
    for j in range(len(invP)):
        invP[i,j] = invP[i,j]%26
K =C*invP
key =''
for i in range(len(invP)):
    for j in range(len(invP)):
        K[i,j] = K[i,j]%26
        key+=chr(int(K[i,j])+ord("a"))
K
key

'hitd'

In [ ]:
def deciphering(plaintext, cipertext, m)
    P = buildMatrix(plaintext,m)
    C = buildMatrix(cipertext,m)
    if(math.gcd(int(detP), 26)==1):
        invP = inv(m)*round(np.linalg.det(P))*modInverse(round(np.linalg.det(P)), 26)
        for i in range(len(invP)):
            for j in range(len(invP)):
                invP[i,j] = invP[i,j]%26

        K = C*invP
        key =''
        for i in range(len(invP)):
            for j in range(len(invP)):
                K[i,j] = K[i,j]%26
                key+=chr(int(K[i,j])+ord("a"))
    else:
        print("Impossibile costruire la matrice inversa P*")
    


In [224]:
key ='c'
key+='i'
key

'ci'